### PR TITLE
Added safe render function and applied it to views

### LINKED ISSUE #8: Use SafeAreaView to respect safe areas
Our RN views are getting in to problems with not respecting safe areas - we should fix this in the RN bundles so they'll look right in-app

https://facebook.github.io/react-native/docs/safeareaview

screen shot 2018-12-04 at 5 20 22 pm
screen shot 2018-12-04 at 5 20 07 pm

### PR DESCRIPTION
**Pull request by Tavaru5**
## Description
Created a safeRender helper method to encapsulate a view in a SafeAreaView, and then added it to each of the views' render methods

## Motivation and Context
Closes #8 

## How Has This Been Tested?
Testing for this was all done locally by opening the views on an iPhone X simulator and rotating them to make sure that they were not cut off by the notch.

## Screenshots
screen shot 2019-02-28 at 9 54 23 pm

### CODE REVIEW

**Review by ZachOrr — COMMENTED** [review]
Can we call `safeRender` in the root `MatchBreakdown` so all of the subclasses get this functionality without having to repeat it? I’m not sure if that’s possible with the way `render` works with superclasss

**Comment by dracco1993** [comment]
Yeah, we should be able to do this.  It may require adding another method to the parent, but it should certainly be possible.

**Comment by Tavaru5** [comment]
We can add it to the superclass so that they don't need to import safeRender, but to my knowledge we can't do it without calling something in the subclass.

**Comment by ZachOrr** [comment]
Are there protocols in RN? Or we can just force the subviews to return their root view via a property

**Comment by Tavaru5** [comment]
I'm not sure what you mean by protocols, but we could have the the subviews return a root view for the superclass render method (if that's what you were talking about). A few people I talked to about this mentioned that [higher order components](https://reactjs.org/docs/higher-order-components.html) would work, but I don't know if we need them.

**Comment by ZachOrr** [comment]
Yes! This high order component pattern seems right. Possibly overkill for what we have to do, but looks like the right pattern.

**Comment by ZachOrr** [comment]
For context - my concern is for anyone building new match breakdown views. They shouldn't have to worry about making sure their view is wrapped in another view - they should hopefully get that functionality/safety for free.

Although - there's only been two people that have ever built a match breakdown view for now, so if it's too much work we can always table this as a "nice to have", file and issue, and get this merged

**Comment by Tavaru5** [comment]
So for the higher order components, I've tried a few things. We can't wrap the export from the superclass (`MatchBreakdown.js`) in an HOC, because it prevents the subclass from accessing superclass methods. Additionally, since it just changes the render method, it gets overwritten by the subclass render method.  
Wrapping the export from the subclass works, but we still would have to extend the superclass, since we can't move methods into the HOC, so it ends up being similar to what's currently in this PR, except `safeRender` isn't called in the render method anymore, it's moved to the export line where we would do something like `export default const MatchBreakdown2019Safe = safeRender(MatchBreakdown2019)`.  
We can move to that, since I think it's better practice, but I don't know if there's a way to solve the issue with building new match breakdown views not needing to worry about including that method.

**Comment by ZachOrr** [comment]
Going to merge this - the discussion feels too long for such a small feature. If we wanna clean it up later, we can. It's a small repo.

**Pull request merged**
